name: release

on:
  push:
    tags:
      - "v*"
jobs:
  tagged-release:
    name: "Tagged Release Final"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: 22
          distribution: 'temurin'
      - name: Build with Gradle
        run: ./gradlew clean build --info --stacktrace
      - uses: softprops/action-gh-release@v2
        with:
          files: |
            ./build/libs/xlr-advanced-gating-plugin-*.*